# Generated by Django 3.2.18 on 2023-05-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sname', models.CharField(max_length=100)),
                ('sage', models.IntegerField(primary_key=True, serialize=False)),
                ('saddress', models.TextField(max_length=200)),
                ('squalification', models.CharField(max_length=10)),
            ],
        ),
    ]
